import {formatStatementSummary} from '../core/describe.js'
import type {PlanEntry} from '../core/plan.js'
import {renderMarkdown} from './diff.js'
import {style} from './style.js'

/** Lets CI find and update its previous comment instead of adding a new one. */
export const PLAN_MARKER = '<!-- timemachine-plan -->'

const LABEL: Record<PlanEntry['status'], string> = {
  changes: 'ready to apply',
  'in-sync': 'in sync',
  'no-snapshot': 'no snapshot in this commit',
  'base-drifted': 'Copado changed since the last snapshot: apply will refuse',
  error: 'error',
}

const ICON: Record<PlanEntry['status'], string> = {
  changes: '✅',
  'in-sync': '✔️',
  'no-snapshot': '➖',
  'base-drifted': '⚠️',
  error: '❌',
}

function label(e: PlanEntry): string {
  if (e.status === 'changes' && e.saveBlockers.length > 0) return 'Copado would reject it: required fields empty'
  return e.status === 'error' ? `error: ${e.error?.message}` : LABEL[e.status]
}

function icon(e: PlanEntry): string {
  return e.status === 'changes' && e.saveBlockers.length > 0 ? '⛔' : ICON[e.status]
}

export function renderPlanText(entries: PlanEntry[], ref: string): string {
  const lines = [style.bold(`Time Machine plan: ${ref} → Copado`), '']
  for (const e of entries) {
    const head = e.statements.length > 0 ? formatStatementSummary(e.summary) : ''
    const colour = e.status === 'changes' && e.saveBlockers.length === 0 ? style.green : e.status === 'in-sync' ? style.dim : style.yellow
    lines.push(`${style.bold(e.template.name)}  ${colour(label(e))}${head ? style.dim(`  (${head})`) : ''}`)
    for (const s of e.statements) lines.push(`  ${s.sign} ${s.text}`)
    if (e.status === 'base-drifted') {
      lines.push(style.yellow('  Changed in Copado since the last snapshot:'))
      for (const s of e.driftSinceBase) lines.push(style.yellow(`    ${s.sign} ${s.text}`))
    }
    for (const b of e.saveBlockers) lines.push(style.red(`  ⛔ ${b.fix}`))
    lines.push('')
  }
  const ready = entries.filter((e) => e.status === 'changes' && e.saveBlockers.length === 0).length
  lines.push(
    ready > 0 ? `${ready} template${ready === 1 ? '' : 's'} would change. Apply with: agentia timemachine apply` : 'Nothing to apply.',
  )
  return lines.join('\n')
}

/** Markdown for a pull-request comment. */
export function renderPlanMarkdown(entries: PlanEntry[], ref: string): string {
  const lines = [
    PLAN_MARKER,
    `### ⏱️ Time Machine plan · \`${ref}\``,
    '',
    '| | Template | Change | Status |',
    '| --- | --- | --- | --- |',
    ...entries.map(
      (e) =>
        `| ${icon(e)} | ${cell(e.template.name)} | ${e.statements.length > 0 ? formatStatementSummary(e.summary) : '—'} | ${cell(label(e))} |`,
    ),
  ]
  for (const e of entries.filter((x) => x.statements.length > 0)) {
    lines.push('', renderMarkdown(e.statements, e.summary, {title: e.template.name, from: 'Copado now', to: ref}))
    if (e.status === 'base-drifted') {
      lines.push('', `> ⚠️ **${cell(e.template.name)} was changed in Copado after its last snapshot.** Apply will refuse to overwrite it:`)
      lines.push('>', '> ```diff', ...e.driftSinceBase.map((s) => `> ${s.sign === '~' ? '!' : s.sign} ${s.text}`), '> ```')
      lines.push('>', '> Run `agentia timemachine snapshot` and rebase this change on the new snapshot.')
    }
    for (const b of e.saveBlockers) lines.push('', `> ⛔ ${b.fix}`)
  }
  lines.push('', '<sub>Generated by `agentia timemachine plan`. After merge, apply with `agentia timemachine apply`.</sub>')
  return lines.join('\n')
}

function cell(text: string): string {
  return text.replace(/\|/g, '\\|')
}
