import {spawn} from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

import {Args, Flags} from '@oclif/core'

import {TimemachineCommand} from '../../base-command.js'
import {buildReport, type ReportData} from '../../core/report.js'
import {renderReportHtml} from '../../render/report-html.js'
import {style} from '../../render/style.js'
import {Store} from '../../store/store.js'
import {findTracked} from './history.js'

export interface ReportResult {
  file: string
  templates: number
  versions: number
  live: boolean
}

export default class TimemachineReport extends TimemachineCommand {
  static override summary = 'Write a visual HTML report: timelines, readable diffs, live status, checks.'
  static override description = `Builds one self-contained HTML page (no network needed to view it) for the tracked templates:
each template's version timeline (who, when, why, what changed, restore command), whether Copado changed since
the last snapshot, what Copado's data engine will use (verify), and lint findings.

The page contains your template configuration; it is written inside the workspace and git-ignored.
Use --offline to build it from git history only (no Copado calls).`

  static override examples = [
    '<%= config.bin %> <%= command.id %> --open',
    '<%= config.bin %> <%= command.id %> "TM Demo - Accounts New" --output ~/Desktop/templates.html',
    '<%= config.bin %> <%= command.id %> --offline',
  ]

  static override strict = false
  static override args = {
    templates: Args.string({description: 'Tracked template names, Ids or slugs (default: all tracked).', required: false}),
  }

  static override flags = {
    output: Flags.string({char: 'o', description: 'Where to write the HTML (default: .timemachine/report.html).'}),
    open: Flags.boolean({description: 'Open the report in the default browser.'}),
    offline: Flags.boolean({description: 'Use git history only; do not read Copado.'}),
    limit: Flags.integer({char: 'n', description: 'Show at most this many versions per template.'}),
  }

  public async run(): Promise<ReportResult> {
    const {argv, flags} = await this.parse(TimemachineReport)
    const store = Store.require(process.cwd())
    const config = store.loadConfig()
    const refs = argv as string[]
    const tracked = refs.length > 0 ? refs.map((r) => findTracked(config.templates, r)) : config.templates

    let data: ReportData
    if (flags.offline) {
      data = await buildReport(store, config, tracked, {limit: flags.limit})
    } else {
      const client = this.createClient(store.root)
      await client.assertSupportedVersion()
      data = await buildReport(store, config, tracked, {client, listed: await client.listTemplates(), limit: flags.limit})
    }

    const file = path.resolve(flags.output ?? path.join(store.dir, 'report.html'))
    fs.mkdirSync(path.dirname(file), {recursive: true})
    fs.writeFileSync(file, renderReportHtml(data))
    ensureIgnored(store)

    const versions = data.templates.reduce((n, t) => n + t.versions.length, 0)
    if (!this.jsonEnabled()) {
      this.log(`${style.green('✔')} Report written: ${file}`)
      this.log(
        style.dim(
          `  ${data.templates.length} template${data.templates.length === 1 ? '' : 's'}, ${versions} versions${flags.offline ? ' (offline: git history only)' : ''}`,
        ),
      )
    }
    if (flags.open) openInBrowser(file)
    return {file, templates: data.templates.length, versions, live: !flags.offline}
  }
}

/** The report contains org configuration: keep it out of git. */
function ensureIgnored(store: Store): void {
  const gitignore = path.join(store.dir, '.gitignore')
  const current = fs.existsSync(gitignore) ? fs.readFileSync(gitignore, 'utf8') : ''
  if (!current.split('\n').includes('report.html'))
    fs.writeFileSync(gitignore, `${current.trimEnd()}\n# generated by timemachine report\nreport.html\n`)
}

function openInBrowser(file: string): void {
  const opener = process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'explorer' : 'xdg-open'
  spawn(opener, [file], {detached: true, stdio: 'ignore'}).unref()
}
