#!/usr/bin/env node
/** Regenerates docs/open-source.md: every runtime dependency (direct and transitive) with its licence. */
import {execFileSync} from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'))
const dirs = execFileSync('npm', ['ls', '--omit=dev', '--all', '--parseable'], {encoding: 'utf8'}).trim().split('\n').slice(1)
const seen = new Map()
for (const dir of dirs) {
  const m = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'))
  const license =
    typeof m.license === 'string' ? m.license : (m.license?.type ?? (m.licenses ?? []).map((l) => l.type).join(' OR ') ?? 'UNKNOWN')
  seen.set(`${m.name}@${m.version}`, {name: m.name, version: m.version, license, direct: m.name in (pkg.dependencies ?? {})})
}
const rows = [...seen.values()].sort((a, b) => Number(b.direct) - Number(a.direct) || a.name.localeCompare(b.name))
const counts = {}
for (const r of rows) counts[r.license] = (counts[r.license] ?? 0) + 1
const dev = Object.keys(pkg.devDependencies ?? {}).map((name) => {
  const m = JSON.parse(fs.readFileSync(path.join('node_modules', name, 'package.json'), 'utf8'))
  return `| ${name} | ${m.version} | ${m.license} |`
})
const md = `# Open-source components

Time Machine is released under the [MIT licence](../LICENSE). It uses the open-source components below, all under
permissive licences. Generated by \`node scripts/licenses.mjs\`.

**Runtime** (shipped with the plugin): ${rows.length} packages: ${Object.entries(counts)
  .sort((a, b) => b[1] - a[1])
  .map(([l, n]) => `${n} ${l}`)
  .join(', ')}.

| Package | Version | Licence | Direct |
| --- | --- | --- | --- |
${rows.map((r) => `| ${r.name} | ${r.version} | ${r.license} | ${r.direct ? 'yes' : ''} |`).join('\n')}

**Development only** (build, test and lint; not shipped):

| Package | Version | Licence |
| --- | --- | --- |
${dev.join('\n')}

Time Machine calls the Copado Agentia™ CLI (\`@copado/agentia-cli\`) as an external program; it does not include or
import its code.
`
fs.writeFileSync('docs/open-source.md', md)
console.log(`docs/open-source.md: ${rows.length} runtime + ${dev.length} dev packages`)
